//
// Created by xjh on 2018/8/29.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testjni_myJNI */

#ifndef _Included_com_example_testjni_myJNI
#define _Included_com_example_testjni_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testjni_myJNI
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_testjni_myJNI_sayHello
  (JNIEnv *env, jclass job, jstring str){
  return (*env)->NewStringUTF(env,"JNI"+str);
  }

#ifdef __cplusplus
}
#endif
#endif
